"""empty message

Revision ID: 2c5379165609
Revises: 03dc0f974cde
Create Date: 2018-07-10 22:23:25.984031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5379165609'
down_revision = '03dc0f974cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'title')
    # ### end Alembic commands ###
