"""empty message

Revision ID: 4bc569f62e23
Revises: 0950db6e5ccc
Create Date: 2018-07-10 09:48:37.073490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc569f62e23'
down_revision = '0950db6e5ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocs', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blocs', 'locations', ['location_id'], ['id'])
    op.drop_column('blocs', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocs', sa.Column('location', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blocs', type_='foreignkey')
    op.drop_column('blocs', 'location_id')
    # ### end Alembic commands ###
