"""empty message

Revision ID: 736f39b16032
Revises: 8b60829685a2
Create Date: 2018-07-08 20:10:07.681867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736f39b16032'
down_revision = '8b60829685a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocs_platforms', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blocs_platforms', 'statuses', ['status_id'], ['id'])
    op.drop_column('blocs_platforms', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocs_platforms', sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blocs_platforms', type_='foreignkey')
    op.drop_column('blocs_platforms', 'status_id')
    # ### end Alembic commands ###
