"""empty message

Revision ID: 8b60829685a2
Revises: 2208de96f000
Create Date: 2018-07-08 18:22:57.614771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b60829685a2'
down_revision = '2208de96f000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_authors', sa.Column('bloc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_authors', 'blocs', ['bloc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_authors', type_='foreignkey')
    op.drop_column('project_authors', 'bloc_id')
    # ### end Alembic commands ###
