"""empty message

Revision ID: da3af31c2944
Revises: 4bc569f62e23
Create Date: 2018-07-10 10:56:24.750483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3af31c2944'
down_revision = '4bc569f62e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocs', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocs', 'is_default')
    # ### end Alembic commands ###
