"""empty message

Revision ID: 0950db6e5ccc
Revises: 4e446c5e100f
Create Date: 2018-07-08 22:40:49.589669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0950db6e5ccc'
down_revision = '4e446c5e100f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocs', sa.Column('location', sa.String(length=32), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('blocs', 'location')
    # ### end Alembic commands ###
