"""empty message

Revision ID: 2208de96f000
Revises: 
Create Date: 2018-07-08 18:12:48.917398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2208de96f000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('blocs', sa.Column('invite_code', sa.String(length=6), nullable=True))
    op.add_column('blocs', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('blocs', sa.Column('theme_color', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'blocs', 'users', ['created_by'], ['id'])
    op.add_column('courses', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('courses', sa.Column('title', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'courses', 'users', ['created_by_id'], ['id'])
    op.add_column('jobs', sa.Column('max_salary', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('min_salary', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.drop_column('jobs', 'salary_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'min_salary')
    op.drop_column('jobs', 'max_salary')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'title')
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'created_by_id')
    op.drop_constraint(None, 'blocs', type_='foreignkey')
    op.drop_column('blocs', 'theme_color')
    op.drop_column('blocs', 'is_private')
    op.drop_column('blocs', 'invite_code')
    op.drop_column('blocs', 'created_by')
    # ### end Alembic commands ###
