"""empty message

Revision ID: 7ad9278325aa
Revises: 7b4fcd2cf265
Create Date: 2018-07-10 23:01:15.168347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad9278325aa'
down_revision = '7b4fcd2cf265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('coordinates', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'coordinates')
    # ### end Alembic commands ###
