"""empty message

Revision ID: 7b4fcd2cf265
Revises: 2c5379165609
Create Date: 2018-07-10 22:56:25.408552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4fcd2cf265'
down_revision = '2c5379165609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'coordinates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('coordinates', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
