"""empty message

Revision ID: 161602b37c91
Revises: 96a57c0fd7de
Create Date: 2018-07-18 18:35:48.431994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161602b37c91'
down_revision = '96a57c0fd7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocs', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blocs', 'statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blocs', type_='foreignkey')
    op.drop_column('blocs', 'status_id')
    # ### end Alembic commands ###
