"""empty message

Revision ID: 27965359fa8a
Revises: 161602b37c91
Create Date: 2018-07-18 18:52:28.606709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27965359fa8a'
down_revision = '161602b37c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'created_by_id')
    # ### end Alembic commands ###
