"""empty message

Revision ID: 33847007b2a9
Revises: 
Create Date: 2018-07-17 09:22:49.671215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33847007b2a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('blocs', sa.Column('invite_code', sa.String(length=6), nullable=True))
    op.add_column('blocs', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('blocs', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('blocs', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('blocs', sa.Column('theme_color', sa.String(length=8), nullable=True))
    op.create_foreign_key(None, 'blocs', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'blocs', 'users', ['created_by'], ['id'])
    op.add_column('courses', sa.Column('bloc_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('days_of_week', sa.TEXT(), nullable=True))
    op.add_column('courses', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('courses', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('courses', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('courses', sa.Column('thumbnail', sa.TEXT(), nullable=True))
    op.add_column('courses', sa.Column('time', sa.String(length=6), nullable=True))
    op.add_column('courses', sa.Column('title', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'courses', 'blocs', ['bloc_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'users', ['created_by_id'], ['id'])
    op.add_column('jobs', sa.Column('max_salary', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('min_salary', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.drop_column('jobs', 'salary_amount')
    op.add_column('locations', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('project_authors', sa.Column('bloc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_authors', 'blocs', ['bloc_id'], ['id'])
    op.drop_column('schools', 'category')
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('blocs_platform_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'users', 'blocs_platforms', ['blocs_platform_id'], ['id'])
    op.drop_column('users', 'location')
    op.drop_column('users', 'blocs_platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocs_platform', mysql.VARCHAR(length=16), nullable=True))
    op.add_column('users', sa.Column('location', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'blocs_platform_id')
    op.drop_column('users', 'avatar_url')
    op.add_column('schools', sa.Column('category', mysql.ENUM('C++', 'C#', 'Java', 'Perl', 'Python', 'JavaScript', 'PHP', 'CSS', 'HTML'), nullable=True))
    op.drop_constraint(None, 'project_authors', type_='foreignkey')
    op.drop_column('project_authors', 'bloc_id')
    op.drop_column('locations', 'title')
    op.add_column('jobs', sa.Column('salary_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True))
    op.drop_column('jobs', 'min_salary')
    op.drop_column('jobs', 'max_salary')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'title')
    op.drop_column('courses', 'time')
    op.drop_column('courses', 'thumbnail')
    op.drop_column('courses', 'start_date')
    op.drop_column('courses', 'end_date')
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'days_of_week')
    op.drop_column('courses', 'created_by_id')
    op.drop_column('courses', 'bloc_id')
    op.drop_constraint(None, 'blocs', type_='foreignkey')
    op.drop_constraint(None, 'blocs', type_='foreignkey')
    op.drop_column('blocs', 'theme_color')
    op.drop_column('blocs', 'location_id')
    op.drop_column('blocs', 'is_private')
    op.drop_column('blocs', 'is_default')
    op.drop_column('blocs', 'invite_code')
    op.drop_column('blocs', 'created_by')
    # ### end Alembic commands ###
