"""empty message

Revision ID: 96a57c0fd7de
Revises: 33847007b2a9
Create Date: 2018-07-18 18:32:44.903570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a57c0fd7de'
down_revision = '33847007b2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'status_id')
    # ### end Alembic commands ###
