"""empty message

Revision ID: 9c00634516f6
Revises: 38a277160223
Create Date: 2018-07-18 22:16:13.786259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c00634516f6'
down_revision = '38a277160223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('weblink', sa.String(length=256), nullable=True))
    op.drop_column('projects', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('url', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('projects', 'weblink')
    # ### end Alembic commands ###
